import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import test from 'node:test';

import { reconcileProcessAdoption } from '../scripts/reconcile-process-adoption.mjs';

const repository = 'phuongnse/renovate-ops';
const checkpoint = 'a'.repeat(40);
const headSha = 'b'.repeat(40);
const token = 't'.repeat(40);
const consumer = {
  repository,
  defaultBranch: 'main',
  checkpoint,
  configPath: '.github/renovate.json',
  configSha256: `sha256:${'c'.repeat(64)}`,
};

function fileDocument(content) {
  const bytes = Buffer.from(content, 'utf8');
  return {
    type: 'file',
    encoding: 'base64',
    content: bytes.toString('base64'),
    size: bytes.length,
  };
}

function candidate(version) {
  const source = `--only-binary :all:\n\nengineering-process==${version}\n`;
  const command = '#    pip-compile --generate-hashes --no-emit-index-url --output-file=requirements/process.txt --strip-extras requirements/process.in';
  const requirements = `#\n# This file is autogenerated by pip-compile with Python 3.12\n# by the following command:\n#\n${command}\n#\n--only-binary :all:\n\nengineering-process==${version} \\\n    --hash=sha256:${'d'.repeat(64)}\n`;
  const lock = `${JSON.stringify({
    schemaVersion: 1,
    process: {
      package: 'engineering-process',
      version,
      digest: `sha256:${'e'.repeat(64)}`,
    },
    requirementsDigest: `sha256:${createHash('sha256').update(requirements).digest('hex')}`,
    skills: ['run-change'],
    managedFiles: ['.agents/skills/run-change/SKILL.md'],
  }, null, 2)}\n`;
  return {
    '.process/process.lock': fileDocument(lock),
    'requirements/process.in': fileDocument(source),
    'requirements/process.txt': fileDocument(requirements),
  };
}

function pullRequest({
  number = 42,
  branch = 'automation/renovate/engineering-process',
  ref = headSha,
  version = '1.1.0',
  headRepository = repository,
  draft = true,
  baseSha = checkpoint,
  baseRepository = repository,
} = {}) {
  return {
    number,
    state: 'open',
    draft,
    head: { ref: branch, sha: ref, repo: { full_name: headRepository } },
    base: { ref: 'main', sha: baseSha, repo: { full_name: baseRepository } },
    version,
  };
}

function response(document, status = 200) {
  const bytes = status === 204 ? Buffer.alloc(0) : Buffer.from(JSON.stringify(document));
  return {
    ok: status >= 200 && status < 300,
    status,
    headers: { get: (name) => name.toLowerCase() === 'content-length' ? String(bytes.length) : null },
    arrayBuffer: async () => bytes,
  };
}

function fixture({
  mainVersion = '1.0.0',
  pulls = [pullRequest()],
  versions = { [headSha]: '1.1.0' },
} = {}) {
  const calls = [];
  const mainFiles = candidate(mainVersion);
  const filesByRef = Object.fromEntries(
    Object.entries(versions).map(([ref, version]) => [ref, candidate(version)]),
  );
  const fetchImpl = async (rawUrl, options = {}) => {
    const url = new URL(rawUrl);
    const method = options.method ?? 'GET';
    calls.push({
      body: options.body,
      method,
      path: url.pathname,
      search: url.search,
    });
    if (url.pathname === `/repos/${repository}/pulls` && method === 'GET') {
      return response(pulls);
    }
    if (url.pathname.startsWith(`/repos/${repository}/contents/`) && method === 'GET') {
      const path = url.pathname.slice(`/repos/${repository}/contents/`.length);
      const ref = url.searchParams.get('ref');
      const document = ref === checkpoint
        ? mainFiles[path]
        : filesByRef[ref]?.[path];
      return document ? response(document) : response({ message: 'Not Found' }, 404);
    }
    if (method === 'POST' && url.pathname === `/repos/${repository}/issues/42/comments`) {
      return response({ id: 101 }, 201);
    }
    if (method === 'DELETE' && url.pathname.includes('/git/refs/heads/')) {
      return response(null, 204);
    }
    if (method === 'PATCH' && url.pathname === `/repos/${repository}/pulls/42`) {
      return response({ state: 'closed' });
    }
    throw new Error(`unexpected GitHub API request: ${method} ${url.pathname}${url.search}`);
  };
  return { calls, fetchImpl };
}

function mutations(calls) {
  return calls.filter(({ method }) => method !== 'GET');
}

test('stale exact process candidate is commented, deleted, and closed', async () => {
  const { calls, fetchImpl } = fixture({
    pulls: [pullRequest({ baseSha: 'f'.repeat(40) })],
  });
  const result = await reconcileProcessAdoption({
    consumer,
    fetchImpl,
    releaseVersion: '1.2.0',
    token,
  });

  assert.equal(result.status, 'reconciled');
  assert.deepEqual(result.reconciled, [{
    branch: 'automation/renovate/engineering-process',
    number: 42,
    previousVersion: '1.1.0',
  }]);
  assert.deepEqual(mutations(calls).map(({ method }) => method), ['POST', 'DELETE', 'PATCH']);
  assert.match(JSON.parse(mutations(calls)[0].body).body, /1\.1\.0.*1\.2\.0/);
});

test('exact release candidates and foreign branches remain untouched', async (t) => {
  await t.test('exact release candidate', async () => {
    const { calls, fetchImpl } = fixture({
      pulls: [pullRequest({ version: '1.2.0' })],
      versions: { [headSha]: '1.2.0' },
    });
    const result = await reconcileProcessAdoption({
      consumer, fetchImpl, releaseVersion: '1.2.0', token,
    });
    assert.equal(result.status, 'nothing-to-reconcile');
    assert.deepEqual(mutations(calls), []);
  });

  await t.test('exact release candidate with moved base checkpoint is refreshed', async () => {
    const { calls, fetchImpl } = fixture({
      pulls: [pullRequest({ version: '1.2.0', baseSha: 'f'.repeat(40) })],
      versions: { [headSha]: '1.2.0' },
    });
    const result = await reconcileProcessAdoption({
      consumer, fetchImpl, releaseVersion: '1.2.0', token,
    });
    assert.equal(result.status, 'reconciled');
    assert.equal(result.reconciled[0].previousVersion, '1.2.0');
    assert.deepEqual(mutations(calls).map(({ method }) => method), ['POST', 'DELETE', 'PATCH']);
    assert.match(JSON.parse(mutations(calls)[0].body).body, /older consumer checkpoint/);
  });

  await t.test('candidate equal to main is stale after a newer release', async () => {
    const { calls, fetchImpl } = fixture({
      mainVersion: '1.1.0',
      pulls: [pullRequest({ version: '1.1.0' })],
      versions: { [headSha]: '1.1.0' },
    });
    const result = await reconcileProcessAdoption({
      consumer, fetchImpl, releaseVersion: '1.2.0', token,
    });
    assert.equal(result.status, 'reconciled');
    assert.equal(result.reconciled[0].previousVersion, '1.1.0');
    assert.deepEqual(mutations(calls).map(({ method }) => method), ['POST', 'DELETE', 'PATCH']);
  });

  await t.test('versioned process branch', async () => {
    const { calls, fetchImpl } = fixture({
      pulls: [pullRequest({ branch: 'automation/renovate/engineering-process-v1.1.0' })],
    });
    const result = await reconcileProcessAdoption({
      consumer, fetchImpl, releaseVersion: '1.2.0', token,
    });
    assert.equal(result.status, 'reconciled');
    assert.deepEqual(mutations(calls).map(({ method }) => method), ['POST', 'DELETE', 'PATCH']);
  });

  await t.test('major process branches', async () => {
    for (const branch of [
      'automation/renovate/major-engineering-process',
      'automation/renovate/major-engineering-process-v1.1.0',
    ]) {
      const { calls, fetchImpl } = fixture({ pulls: [pullRequest({ branch })] });
      const result = await reconcileProcessAdoption({
        consumer, fetchImpl, releaseVersion: '1.2.0', token,
      });
      assert.equal(result.status, 'reconciled');
      assert.equal(result.reconciled[0].branch, branch);
      assert.deepEqual(mutations(calls).map(({ method }) => method), ['POST', 'DELETE', 'PATCH']);
    }
  });

  await t.test('unrelated owned Renovate branch', async () => {
    const unrelated = pullRequest({ branch: 'automation/renovate/major-github-artifact-actions' });
    const { calls, fetchImpl } = fixture({ pulls: [unrelated] });
    const result = await reconcileProcessAdoption({
      consumer, fetchImpl, releaseVersion: '1.2.0', token,
    });
    assert.equal(result.status, 'nothing-to-reconcile');
    assert.deepEqual(mutations(calls), []);
  });

  await t.test('foreign branch', async () => {
    const foreign = pullRequest({ headRepository: 'someone/renovate-ops' });
    const { calls, fetchImpl } = fixture({ pulls: [foreign] });
    const result = await reconcileProcessAdoption({
      consumer, fetchImpl, releaseVersion: '1.2.0', token,
    });
    assert.equal(result.status, 'nothing-to-reconcile');
    assert.deepEqual(mutations(calls), []);
  });
});

test('newer, malformed, and ambiguous candidates fail closed before mutation', async (t) => {
  await t.test('newer candidate', async () => {
    const { calls, fetchImpl } = fixture({
      versions: { [headSha]: '1.3.0' },
    });
    await assert.rejects(
      reconcileProcessAdoption({ consumer, fetchImpl, releaseVersion: '1.2.0', token }),
      /must not be newer/,
    );
    assert.deepEqual(mutations(calls), []);
  });

  await t.test('malformed owned pull request', async () => {
    const { calls, fetchImpl } = fixture({ pulls: [pullRequest({ draft: false })] });
    await assert.rejects(
      reconcileProcessAdoption({ consumer, fetchImpl, releaseVersion: '1.2.0', token }),
      /not one exact open draft/,
    );
    assert.deepEqual(mutations(calls), []);
  });

  await t.test('ambiguous stale candidates', async () => {
    const secondSha = 'c'.repeat(40);
    const second = pullRequest({ number: 43, ref: secondSha, version: '1.1.0' });
    const { calls, fetchImpl } = fixture({
      pulls: [pullRequest(), second],
      versions: { [headSha]: '1.1.0', [secondSha]: '1.1.1' },
    });
    await assert.rejects(
      reconcileProcessAdoption({ consumer, fetchImpl, releaseVersion: '1.2.0', token }),
      /ambiguous process adoption candidates/,
    );
    assert.deepEqual(mutations(calls), []);
  });
});
